[package]
name = "demo"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portus = "0.5.4" # portus = "0.6.1"
slog = "2"
slog-async = "2"
slog-term = "2"
time = "0.1"
clap = "2.29"
